# Generated by Django 5.2.6 on 2025-11-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='Enterprise',
            new_name='enterprise',
        ),
        migrations.RenameField(
            model_name='box',
            old_name='Sector',
            new_name='sector',
        ),
        migrations.AddField(
            model_name='box',
            name='discard_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Descarte'),
        ),
    ]
